export type Good = "food" | "timber" | "tools";
export type Stocks = Record<Good, number>;
export type Livelihood = "farmer" | "woodcutter" | "toolmaker";

export type BasinCell = {
  id: number;
  x: number;
  z: number;
  elevation: number;
  moisture: number;
  fertility: number;
  forest: number;
  river: boolean;
  downstream: number | null;
  settlementId: string | null;
};
export type BasinWorld = { seed: number; width: number; height: number; cells: BasinCell[]; settlements: { id: string; name: string; x: number; z: number; specialty: Livelihood }[] };
export type Household = {
  id: string;
  settlementId: string;
  size: number;
  livelihood: Livelihood;
  parcelId: number;
  stocks: Stocks;
  coin: number;
  wellbeing: number;
  hardship: number;
  lastMoved: number;
};
export type Settlement = {
  id: string;
  name: string;
  x: number;
  z: number;
  specialty: Livelihood;
  taxRate: number;
  treasury: number;
  bridge: boolean;
  bridgeProgress: number;
  legitimacy: number;
  population: number;
  households: number;
  stocks: Stocks;
  prices: Stocks;
  production: Stocks;
  consumption: Stocks;
  imports: Stocks;
  exports: Stocks;
  migrants: number;
};
export type Route = { id: string; from: string; to: string; cells: number[]; distance: number; travelSeasons: number; capacity: number; bridge: boolean; traded: number };
export type Shipment = { id: number; from: string; to: string; buyerId: string; good: Good; amount: number; arrival: number; routeId: string };
export type BasinEvent = { id: number; season: number; kind: "trade" | "migration" | "weather" | "works" | "policy" | "livelihood"; settlementId: string | null; message: string; causes: Record<string, number> };
export type BasinIntervention = { type: "drought"; duration: number } | { type: "bridge"; settlementId: string } | { type: "tax"; settlementId: string; rate: number };
export type BasinHistory = {
  season: number;
  population: number;
  food: number;
  trade: number;
  wellbeing: number;
  foodPrice?: number;
  migration?: number;
  forest?: number;
};
export type BasinState = {
  schema: "tiny-civilization.basin/v1";
  seed: number;
  season: number;
  world: BasinWorld;
  households: Household[];
  settlements: Settlement[];
  routes: Route[];
  shipments: Shipment[];
  droughtUntil: number;
  events: BasinEvent[];
  history: BasinHistory[];
  interventions: { season: number; action: BasinIntervention }[];
  nextEventId: number;
  nextShipmentId: number;
};
